// ************************************************************************
// *                                                                      *
// * Copyright (C) 2014 Bonden i Nol (hakanbrolin@hotmail.com)            *
// *                                                                      *
// * This program is free software; you can redistribute it and/or modify *
// * it under the terms of the GNU General Public License as published by *
// * the Free Software Foundation; either version 2 of the License, or    *
// * (at your option) any later version.                                  *
// *                                                                      *
// ************************************************************************

#ifndef __CONFIG_BITS_H__
#define __CONFIG_BITS_H__

// Implementation notes:
// 1. PIC18F2510 datasheet, Document: DS39636D
//    http://www.microchip.com/
//
// 2. Assumes external clock, Fosc=20MHz.
//
// 3. List of pragma config statements:
//    /opt/gputils/share/doc/gputils-1.4.0/html/PIC18F2510-conf.html
//
// 4. The code generated by SDCC does not work when
//    XINST (extended instruction set) is enabled (SDCC Compiler User Guide) 
//    ==> pragma config XINST=OFF
//

// CONFIG1H
#pragma config IESO=OFF, FCMEN=OFF, OSC=HS

// CONFIG2L
#pragma config BORV=1, BOREN=SBORDIS, PWRT=OFF

// CONFIG2H
#pragma config WDT=OFF

// CONFIG3H
#pragma config MCLRE=ON, LPT1OSC=OFF, PBADEN=OFF, CCP2MX=PORTC

// CONFIG4L
#pragma config DEBUG=OFF, XINST=OFF, LVP=OFF, STVREN=ON

// CONFIG5L
#pragma config CP3=OFF, CP2=OFF, CP1=OFF, CP0=OFF

// CONFIG5H
#pragma config CPB=OFF

// CONFIG6L
#pragma config WRT3=OFF, WRT2=OFF, WRT1=OFF, WRT0=OFF

// CONFIG6H
#pragma config WRTB=OFF, WRTC=OFF

// CONFIG7L
#pragma config EBTR3=OFF, EBTR2=OFF, EBTR1=OFF,  EBTR0=OFF

// CONFIG7H
#pragma config EBTRB=OFF

#endif // __CONFIG_BITS_H__
